### ISSUE TITLE
source code for `dnssec_prover_wasm_bg.wasm`

### ISSUE THREAD

**Issue by AndySchroder** [TheBlueMatt/satsto.me#5]
Where to find the source code for `dnssec_prover_wasm_bg.wasm` ? It is not referenced at all. Is it found here: https://github.com/TheBlueMatt/dnssec-prover or somewhere else?

**Comment by TheBlueMatt** [comment]
Correct, if you fetch that, then `cd wasmpack && wasm-pack build --target web --release` you should get that wasm file. It should be deterministic-ish, though dependencies have probable been updated and I haven't actually checked if its really deterministic.

**Comment by AndySchroder** [comment]
okay, would be nice to include that in a readme file!

**Comment by TheBlueMatt** [comment]
Done.
